### ISSUE TITLE
Feature request: Allow people to invite themselves to slack.

### ISSUE THREAD

**Issue by myself248** [ThisSmartHouse/makermanager#11]
(from Mel's email) Allow people to invite themselves to slack.

Nate's comment: I would love if every Slack user was linkable to a CRM record (except the ones that're manually invited, and I wouldn't be offended in the least if that ability went away and getting someone on slack required creating them a CRM record).

**Comment by coogle** [comment]
This is done. You can attach a CRM user directly to one of the active slack users inside of the i3detroit team from the member manager.
