### ISSUE TITLE
Feature request:  Connect payment processing to membership status - automatically suspend subscriptions, etc.

### ISSUE THREAD

**Issue by myself248** [ThisSmartHouse/makermanager#3]
(from Mel's email)  Connect payment processing to membership status - automatically suspend subscriptions, etc.

Nate's comment: Also automatically turn them back on if delinquent payment made, subject to configurable limits (like if someone's membership has lapsed for a long time, determined by the membership coordinator, don't allow automatic reactivation.)

**Comment by coogle** [comment]
This is mostly already implemented -- save the "don't allow automatic reactivation" bit. Strip doesn't really support that notion, so need to figure out how best to implement it.

Going to close this one but if you feel strongly about not allowing automatic reactivation please open another feature request!
